# @package _global_

# Training settings
demos: 100
num_train_steps: 50000
batch_size: 128
lr: 1e-4
lr_backbone: 1e-5
weight_decay: 1e-4
update_every_steps: 1

# Evaluation settings
eval_every_steps: 5000
log_eval_video: true
vis_every_steps: 1000
save_every_steps: 5000
num_eval_episodes: 25

# Action settings
action_sequence: 20 # ActionSequenceWrapper
execution_length: 1  # If execution_length < action_sequence, we use receding horizon control
temporal_ensemble: true  # Temporal ensemling only applicable to action sequence > 1
temporal_ensemble_gain: 0.01
normalize_action: min_max # min_max, standardization, none

# wandb settings
wandb:  # weight and bias
  use: true
  project: CoA
  name: null
  save_dir: ${exp_root}


# Misc
seed: 1
num_gpus: 1
log_every_steps: 100

# Visual settings
pixels: true
visual_observation_shape: [128, 128]

debug: False

